Models/Detallestb.cs
using System;
using System.Collections.Generic;

namespace carnetutelvt.Models
{
    public partial class Detallestb
    {
        public int Id { get; set; }
        public string? Fullname { get; set; }
        public string? Surnames { get; set; }
        public string? Specialty { get; set; }
        public string? Faculty { get; set; }
        public string? Ci { get; set; }
        public string? Imgcarnet { get; set; }
        public int? Iduser { get; set; }
        public string?  Bloodtype { get; set; }
    public DateTime? Dateupdate { get; set; }
        public DateTime? Datecreate { get; set; }

        public virtual Usertb? IduserNavigation { get; set; }
    }
}

Controllers/UsertbsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Drawing;
using MessagingToolkit.QRCode.Codec;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using carnetutelvt.Models;
using System.Security.Cryptography;
using System.Net.Mail;
using Microsoft.AspNetCore.Hosting;
using System.Net;
using System.Diagnostics.Metrics;
using Microsoft.AspNetCore.Http;
using carnetutelvt.Controllers;
using System.Text;
using System.Reflection;
using Microsoft.Extensions.Hosting;

namespace carnetutelvt.Controllers
{
    public class UsertbsController : Controller
    {
        private readonly rgutelvtContext _context;
        private readonly rgutelvtContext _contextdeta;
        private const string rp0 = "0",rp1="1",dominio="";
        private readonly IWebHostEnvironment _env;
        private readonly IHttpContextAccessor _conter;
        private IConfiguration _configuration;


        public UsertbsController(rgutelvtContext context, rgutelvtContext contextdeta, IWebHostEnvironment env, IHttpContextAccessor conter, IConfiguration configuration)
        {
            _context = context;
            _env = env;
            _conter = conter;
            _contextdeta = contextdeta;
            _configuration= configuration ;

        }

        // GET: Usertbs
        public async Task<IActionResult> Index(string? Email, int? Valor)
        {
           
            if (_conter.HttpContext.Session.GetInt32("Id") == null || _conter.HttpContext.Session.GetInt32("Id") < 0 || _conter.HttpContext.Session.GetString("Rol")!="1")

            {

                return RedirectToAction(nameof(Login));

            }
            else
            {
                ViewData["NumDatos"] = await _context.Usertbs.CountAsync();
                if (Email == null && Valor==10000)
				{
                    var datos = await _context.Usertbs.ToListAsync();
                    ViewData["NumDatosV"] = datos.Count();
                    return View(datos);
                }
                else if (Valor != null)
                {
                    var datos = _context.Usertbs.Take(Convert.ToInt32(Valor));
                    ViewData["NumDatosV"] = datos.Count();
                    return View(datos);
                }
                else if (Email != null )
				{
                    var datos = await _context.Usertbs.Where(u => u.Email.Contains(Email)).ToListAsync();
                    ViewData["NumDatosV"] = datos.Count();
                    return View(datos);
                }
                else
                {
					var datos =  _context.Usertbs.OrderByDescending(x => x.Id).Take(Convert.ToInt32(10));
					ViewData["NumDatosV"] = datos.Count();
					return View(datos);
				}
				
            }
           
        }

        public  IActionResult Chatbot()
        {

            if (_conter.HttpContext.Session.GetInt32("Id") == null || _conter.HttpContext.Session.GetInt32("Id") < 0 )

            {

                return RedirectToAction(nameof(Login));

            }
            else
            {
            
            
                    return View();
             
                
            }

        }

        // Vista para editar Foto Carnet y Contraseña
      

        public async Task<IActionResult> Modifuser(int? id)
        {
            if (_conter.HttpContext.Session.GetInt32("Id") == null || _conter.HttpContext.Session.GetInt32("Id") < 0 )

            {

                return RedirectToAction(nameof(Login));

            }
            else
            {

                if (id == 0 )
                {
                    return NotFound();
                }

                var usertb = await _context.Usertbs.FindAsync(id);
                if (usertb == null)
                {
                    return NotFound();
                }
                ViewData["Datecreate"] = usertb.Datecreate;
                return View(usertb);
            }
        }
        //Editar Contraseña usuarios


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPass(int id,[Bind("Id,Passwords")] Usertb usertb)
        {
            if (usertb.Passwords == null)
            {
                return NotFound();
            }
                if (id != usertb.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        var miObjeto = _context.Usertbs.FirstOrDefault(x => x.Id == id);
                        if (!string.IsNullOrEmpty(usertb.Passwords))
                        {
                            miObjeto.Passwords = EncrypData(usertb.Passwords);
                        }

                   
                        miObjeto.Dateupdate = DateTime.Now;

                        await _context.SaveChangesAsync();

                    ViewData["Error"] = rp1;
                    return RedirectToAction(nameof(Tablero));
                }
                    catch (DbUpdateConcurrencyException)
                    {
                    ViewData["Error"] = rp0;
                    return RedirectToAction(nameof(Tablero));

                }

            }
            ViewData["Error"] = rp0;
            return RedirectToAction(nameof(Tablero));


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditFotoPerfil(int id,[Bind("Id")] Detallestb detallestb,  IFormFile Imgcarnett)
        {
            var dell = new DetallestbsController(_contextdeta, _contextdeta, _env, _conter);
            if (id==0)
            {
                return NotFound();
            }


            try
            {
                var miObjeto = _contextdeta.Detallestbs.FirstOrDefault(x => x.Iduser == id);


                if (miObjeto != null)
                {
                    miObjeto.Dateupdate = DateTime.Now;
             
                if (Imgcarnett != null)
                {
                    if (miObjeto.Imgcarnet != null)
                    {
                        var uploads = Path.Combine(_env.WebRootPath, "uploads\\" + miObjeto.Imgcarnet);
                        System.IO.File.Delete(uploads);
                    }

                    miObjeto.Imgcarnet = await dell.subirimg(Imgcarnett);
                }
                    await _context.SaveChangesAsync();
                }



                ViewData["Error"] = rp1;
                return RedirectToAction(nameof(Tablero));
            }
            catch (DbUpdateConcurrencyException)
            {
                ViewData["Error"] = rp1;
                return RedirectToAction(nameof(Tablero));
            }


           

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditTypeBlo(int id, [Bind("Id")] Detallestb detallestb, string Bloodtype)
        {
            var dell = new DetallestbsController(_contextdeta, _contextdeta, _env, _conter);
            if (id == 0)
            {
                return NotFound();
            }


            try
            {
                var miObjeto = _contextdeta.Detallestbs.FirstOrDefault(x => x.Iduser == id);


                if (miObjeto != null)
                {
                    miObjeto.Dateupdate = DateTime.Now;

                   
                   if (Bloodtype != null)
                    {
                        miObjeto.Bloodtype = Bloodtype.ToString();
                    }
                    await _context.SaveChangesAsync();
                }



                ViewData["Error"] = rp1;
                return RedirectToAction(nameof(Tablero));
            }
            catch (DbUpdateConcurrencyException)
            {
                ViewData["Error"] = rp1;
                return RedirectToAction(nameof(Tablero));
            }




        }







        //Generar Codigo QR


        public void GenerarQr(string webtex)
        {
            QRCodeEncoder code = new QRCodeEncoder();
            Bitmap img = code.Encode(webtex);
            System.Drawing.Image Qr = (System.Drawing.Image)img;
            using (MemoryStream mem = new MemoryStream())
            {
                Qr.Save(mem, System.Drawing.Imaging.ImageFormat.Jpeg);
                byte[] imgbyte = mem.ToArray();
                ViewData["qr"] = "data:image/git;base64,"+Convert.ToBase64String(imgbyte);
            }
        }


        // GET: Usertbs/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (_conter.HttpContext.Session.GetInt32("Id") == null || _conter.HttpContext.Session.GetInt32("Id") < 0)

            {

                return RedirectToAction(nameof(Login));

            }
            else
            {

                if (_conter.HttpContext.Session.GetInt32("Id") != null)

                {
                    var detallestb = new Detallestb();
                    var userdato = new Usertb();
                    if (_conter.HttpContext.Session.GetInt32("Id") > 0)
                    {
                      
                            int? ids = id;
                        
                        

                        detallestb = _contextdeta.Detallestbs.Where(e => e.Iduser == ids).FirstOrDefault();
                        userdato = _context.Usertbs.Where(e => e.Id == ids).FirstOrDefault();
                        if (detallestb == null)
                        {
                            return NotFound();
                        }
                    }

                    ViewData["Iduser"] = new SelectList(_context.Usertbs, "Id", "Id", detallestb.Iduser);
                    ViewData["Datecreate"] = detallestb.Datecreate;
                    ViewData["Imgcarnet"] = detallestb.Imgcarnet;

Views/Detallestbs/Create.cshtml
@model carnetutelvt.Models.Detallestb

@{
    ViewData["Title"] = "CREAR DETALLES DE LOS USUARIOS";
}

<div class="hero">
  <center>  <h1>Crear Usuarios mediante  Admin</h1></center>
    <div class="container">
        
          <form class="form" asp-action="Create">
            <div class="row mb-2">
                <div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
                    <div class="form-group">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                </div>
                 </div>
         <div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
            <div class="form-group">
                
                <input asp-for="Fullname" class="form-control" placeholder="Nombres" />
                <span asp-validation-for="Fullname" class="text-danger"></span>
            </div>
            </div>
                <div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
            <div class="form-group">
                
                        <input asp-for="Surnames" class="form-control" placeholder="Apellidos" />
                <span asp-validation-for="Surnames" class="text-danger"></span>
            </div>
            </div>
         
               
        

                <div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
                    <div class="form-group">
                        <select asp-for="Faculty" class="form-control" aria-label="Elegir Rol"required>
                            <option selected>Facultad</option>
                            <option value="Facultad de Ingenierías">Facultad de Ingenierías</option>
                            <option value="Facultad de Ciencias Sociales y de Servicios">Facultad de Ciencias Sociales y de Servicios</option>
                            <option value="Facultad de Ciencias Administrativas y Económicas">Facultad de Ciencias Administrativas y Económicas</option>
                            <option value="Facultad de Ciencias Agropecuarias">Facultad de Ciencias Agropecuarias</option>
                            <option value="Facultad de la Pedagogía">Facultad de la Pedagogía</option>
                          
                        </select>

                        <span asp-validation-for="Faculty" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
                    <div class="form-group">
                        <select asp-for="Specialty" class="form-control" aria-label="Carrera" required>
                            <option selected>Carrera</option>
                            <option value="Ingeniería Mecánica">Ingeniería Mecánica</option>
                            <option value="Ingeniería Eléctrica">Ingeniería Eléctrica</option>
                            <option value="Ingeniería Química ">Ingeniería Química </option>
                            <option value="Ingeniería en Tecnologías de la Información y Comunicación">Ingeniería en Tecnologías de la Información y Comunicación</option>
                            <option value="Sociología">Sociología</option>
                            <option value="Trabajo Social ">Trabajo Social </option>
                            <option value="Hotelería y Turismo ">Hotelería y Turismo </option>
                            <option value="Ingeniería en Administración de Empresa ">Ingeniería en Administración de Empresa </option>
                            <option value="Ingeniería en Contabilidad y Auditoría ">Ingeniería en Contabilidad y Auditoría </option>
                            <option value="Ingeniería en Comercio ">Ingeniería en Comercio </option>
                            <option value="Ingeniería en Agronomía">Ingeniería en Agronomía</option>
                            <option value="Ingeniería Forestal">Ingeniería Forestal</option>
                            <option value="Ingeniería Zootécnica">Ingeniería Zootécnica</option>
                            <option value="Ciencias Experimentales de las Matemáticas y la Física">Ciencias Experimentales de las Matemáticas y la Física.</option>
                            <option value="Ciencias Experimentales de la Química y Bilogía">Ciencias Experimentales de la Química y Bilogía</option>
                            <option value="Licenciatura en Educación Básica">Licenciatura en Educación Básica</option>
                            <option value="Pedagogía de la lengua y Literatura   ">Pedagogía de la lengua y Literatura   </option>
                            <option value="Pedagogía de la Actividad Física y Deporte ">Pedagogía de la Actividad Física y Deporte </option>
                            <option value="Licenciatura en Educación Inicial ">Licenciatura en Educación Inicial </option>
                        </select>

                        <span asp-validation-for="Specialty" class="text-danger"></span>
                    </div>
                </div>


                <div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
                    <div class="form-group">
                        <select asp-for="Bloodtype" class="form-control" aria-label="Elegir Tipo de Sangre">
                            <option value="" selected>Null</option>
                            <option value="A+">A+</option>
                            <option value="A-">A-</option>
                            <option value="B+">B+</option>
                            <option value="B-">B-</option>
                            <option value="AB+">AB+</option>
                            <option value="AB-">AB-</option>
                            <option value="O+">O+</option>
                            <option value="O-">O-</option>
                           

                        </select>

                        <span asp-validation-for="Bloodtype" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
            <div class="form-group">

                        <input asp-for="Ci"  type="number" class="form-control" required placeholder="CI" maxlength="10"  />
                <span asp-validation-for="Ci" class="text-danger"></span>
            </div>
            </div>
               
                <div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
                    <div class="form-group">
                        <label>Subir imagen</label>
                        <input type="file" name="Imgcarnett" class="form-control" />

                    </div>
                </div>
              <div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
            <div class="form-group">
                <label asp-for="Iduser" class="control-label"></label>
                <select asp-for="Iduser" class ="form-control" asp-items="ViewBag.Iduser"></select>
            </div>
             </div>
           
                <div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            </div>
            </div>
        </form>
        <a type="submit" class="btn btn-dark" asp-action="Index">Back</a>
    </div>

</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Detallestbs/Delete.cshtml
@model carnetutelvt.Models.Detallestb

@{
    ViewData["Title"] = "ELIMINAR DETALLE DE LOS USUARIOS";
}

<div class="hero">
    <center>
        <h1>Eliminarr Usuarios mediante  Admin</h1> <center>
    <div class="container">

        <form asp-action="Delete" class="form">


    

    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fullname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surnames)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surnames)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Specialty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specialty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Faculty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Faculty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ci)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ci)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imgcarnet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imgcarnet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dateupdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dateupdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datecreate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datecreate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IduserNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IduserNavigation.Id)
        </dd>
    </dl>
    
    
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
     
    </form>
      <a type="submit" class="btn btn-dark" asp-action="Index">Back</a>
    </div>
</div>

Views/Detallestbs/Details.cshtml
@model carnetutelvt.Models.Detallestb

@{
    ViewData["Title"] = "MOSTRAR DETALLES DE LOS USUARIOS";
}

<div class="hero">
   <center> <h1>Perfil de detalle de cada usuario</h1> </center>
    <div class="container">
      <form class="form">
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fullname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surnames)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surnames)
        </dd>
        <dt class = "col-sm-2">
          Carrera
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specialty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Faculty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Faculty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ci)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ci)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imgcarnet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imgcarnet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dateupdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dateupdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datecreate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datecreate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IduserNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IduserNavigation.Id)
        </dd>
    </dl>
        </form>

<div>
        <a type="submit" class="btn btn-success" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
        <a type="submit" class="btn btn-dark" asp-action="Index">Back</a>
 </div>
 </div>
 </div>
 
   

Views/Detallestbs/Estudiantes.cshtml
@model carnetutelvt.Models.Detallestb

@{
    ViewData["Title"] = "UTLVTEW";
}

<div class="hero">

    <center> <h1>UTLVTE</h1> </center>
    <div class="container">

        <form class="form">
            <dl class="row">
                <dt class="col-sm-2">
                    NOMBRES:
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Fullname)
                </dd>
                <dt class="col-sm-2">
                    APELLIDOS:
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Surnames)
                </dd>
                <dt class="col-sm-2">
                    FACULTAD:
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Faculty)
                </dd>

            </dl>
        </form>
        <div>
     </div>

Views/Detallestbs/Index.cshtml
@model IEnumerable<carnetutelvt.Models.Detallestb>

@{
    ViewData["Title"] = "UTLVTE DETALLES";
}



<div class="hero">
    
	
    <div class="container">
		
		<section class="ftco-section">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-md-6 text-center mb-4">
						<center>	<h2>Detalles de todos los usuarios: (@ViewData["NumDatosV"]/@ViewData["NumDatos"])</h2></center>
					
					</div>
					
				</div>
				<div class="container">
					<form class="form" asp-action="Index">
						<div class="form-group">
							<input name="Ci" class="form-control" placeholder="Solo Numero de Cedula(Ingesa un numero de cedula)" />

						</div>
						<div class="col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3">
							<div class="form-group">
								<select name="Valor" class="form-control" aria-label="Elegir Tipo de Sangre">

									<option value="" selected>Null</option>
									<option value="50">50</option>
									<option value="100">100</option>
									<option value="1000">1000</option>
									<option value="10000">10000</option>


								</select>


							</div>
						</div>
						<input type="submit" value="Buscar" class="btn btn-info">
					</form>
					<h3><!-- <a type="button" class="btn btn-success" asp-action="Create">Crear Nuevo</a>--><a type="button" class="btn btn-secondary" asp-controller="Usertbs" asp-action="Index">Usuarios</a></h3>
				</div>
				<div class="row">
					<div class="col-md-12">
						
						<div class="table-wrap">
							<table class="table">
								<thead class="thead-primary">
									<tr>
										<th>@Html.DisplayNameFor(model => model.Id)</th>
                                        <th>@Html.DisplayNameFor(model => model.Imgcarnet)</th>
										<th> @Html.DisplayNameFor(model => model.Fullname)</th>
                                        <th> @Html.DisplayNameFor(model => model.Surnames)</th>

                                        <th>Carrera</th>
                                        <th>@Html.DisplayNameFor(model => model.Faculty)</th>
                                        <th>@Html.DisplayNameFor(model => model.Ci)</th>
										<th>@Html.DisplayNameFor(model => model.Bloodtype)</th>
                                        <th>@Html.DisplayNameFor(model => model.Dateupdate)</th>
                                        <th>@Html.DisplayNameFor(model => model.Datecreate)</th>

                                        <th> @Html.DisplayNameFor(model => model.IduserNavigation)</th>
										<th>Edit</th>
										<th>Details</th>
										<th>Delete</th>
                                    </tr>
								</thead>
								<tbody>
                                    @foreach (var item in Model) {
									<tr class="alert" role="alert">
										<td>
												<div class="email">
													<input type="text" value="@Html.DisplayFor(modelItem => item.Id)" readonly>
													<span class="checkmark"></span>
												</div>
										</td>
										<td>

												<img src="/uploads\@Html.DisplayFor(modelItem => item.Imgcarnet) " loading="lazy" alt="Image" class="img-fluid">
											</td>
										<td>
											<div class="email">

													<span><input type="text" value="@Html.DisplayFor(modelItem => item.Fullname)" readonly /></span>
											</div>
										</td>
											<td>
												<div class="email">

													<span><input type="text" value="@Html.DisplayFor(modelItem => item.Surnames)" readonly /></span>
												</div>
											</td>
											<td>
											<div class="email">

													<span><input type="text" value="@Html.DisplayFor(modelItem => item.Specialty)" readonly/></span>
											</div>
										</td>
											<td>
												<div class="email">

													<span><input type="text" value="@Html.DisplayFor(modelItem => item.Faculty)" readonly/></span>
												</div>
											</td>
											<td>
												<div class="email">

													<span><input type="text" value="@Html.DisplayFor(modelItem => item.Ci)" readonly/></span>
												</div>
											</td>
											<td>
												<div class="email">

													<span><input type="text" value="@Html.DisplayFor(modelItem => item.Bloodtype)" readonly /></span>
												</div>
											</td>
											<td>
												<div class="email">

													<span><input type="text" value="@Html.DisplayFor(modelItem => item.Dateupdate)" readonly /></span>
												</div>
											</td>
											<td>
												<div class="email">

													<span><input type="text" value="@Html.DisplayFor(modelItem => item.Datecreate)" readonly /></span>
												</div>
											</td>
											<td>
												<div class="email">

													<span> <textarea>@Html.DisplayFor(modelItem => item.IduserNavigation)  </textarea>  </span>
												</div>
											</td>
										
											<td>
												<div class="email">
													<a type="submit" class="btn btn-success" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
												</div>
											</td>
											<td>
												<div class="email">

													<a type="submit" class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">Details</a>

												</div>
											</td>
											<td>
												<div class="email">

													<a type="submit" class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
												</div>
											</td>
										

									</tr>

									
								}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</section>
		</div>
		</div>